# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 08:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ww', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ww.Source')),
                ('word', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ww.Word')),
            ],
        ),
    ]
